version: '3.8'
services:
  postgres-db:
    restart: always
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zno_results
      - POSTGRES_HOST=postgres-db
    ports:
      - '5432:5432'
    networks:
      - postgres_network

  app:
    build: ./app/
    depends_on:
      postgres-db:
        condition: service_started
    environment:
        PYTHONUNBUFFERED: 1
    volumes:
      - ./app/:/db_lab1/app
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
        - "5050:80"
    networks:
      - postgres_network

networks:
  postgres_network:
